<?php
return [
    '_root_'                => 'top/main/index',
    '_404_'                 => 'start/404',
    'check'                 => 'check',
    'top'                   => 'top/index',
    'client'                => 'client/main/index',
    'advertiser/login'      => 'login/advertiser',
    'advertiser'            => 'advertiser/index',
    'media/login'           => 'login/media',
    'media'                 => 'media/index',
    'system/login'          => 'login/system',
    'admin/(:any)'          => 'admin/$1',
    'admin'                 => 'admin',
    'system'                => 'system',
    'system/(:any)'         => 'system/$1',
    ':accounttype/login'    => 'member/login',
    ':accounttype/logout'   => 'member/logout',
    'advertiser/(:any)'     => 'advertiser/$1',
    'sponsor/(:any)'        => 'sponsor/$1',
    'agency/(:any)'         => 'sponsor/$1',
    'media/(:any)'          => 'media/$1',
    'rep/(:any)'            => 'media/$1',
    ':accounttype'          => 'member',
];
