<?php
return [
    '_root_'  => 'start/index',
    '_404_'   => 'start/404',
    'check' => 'check',
    'client' => 'client',
    'client' => 'client/top/index',
    'client/top' => 'client/top/index',
    'admin/(:any)' => 'admin/$1',
    'admin' => 'admin',
    'system' => 'system',
    'system/(:any)' => 'system/$1',
    ':accounttype/login' => 'member/login',
    ':accounttype/logout' => 'member/logout',
    'sponsor/(:any)' => 'sponsor/$1',
    'agency/(:any)' => 'sponsor/$1',
    'media/(:any)' => 'media/$1',
    'rep/(:any)' => 'media/$1',
    ':accounttype' => 'member',
];
